name: Python Package using Conda

on:
  push:
    branches:
    - main

  workflow_dispatch:
  
jobs:

  # linux build test
  test:

    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
      max-parallel: 5


    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
                
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Installing mamba
      run: |
        conda install -c conda-forge mamba

    - name: Trying conda package installation
      run: |
         mamba create -y -n conda-pip-testing -c conda-forge -c bioconda -c defaults -c astrobiomike conda-pip-testing
 
    - name: Test command
      run: |
         conda activate conda-pip-testing
         print-test
