name: Python Package using Conda

on:
  push:
    branches:
    - main

  workflow_dispatch:
  
jobs:

  # linux and mac build tests
  test:

    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
      max-parallel: 5


    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4.2.0
      with:
        python-version: "3.10"
                
    - name: Add conda to system path and initializing it for the shell
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        
        echo $0
        
        conda init bash
        
        tail ~/.bashrc
        
        source ~/.bashrc
        
        which conda

    - name: Installing mamba
      run: |
        conda install -c conda-forge mamba

    - name: Trying conda package installation
      run: |
         mamba create -y -n conda-pip-testing -c conda-forge -c bioconda -c defaults -c astrobiomike conda-pip-testing
 
    - name: Test command
      run: |
         source activate conda-pip-testing
         print-test
